[project]
name = 'stackup'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.bounty-escrow]
path = 'contracts/bounty-escrow.clar'
clarity_version = 3
epoch = '3.2'

[contracts.milestone-escrow]
path = 'contracts/milestone-escrow.clar'
clarity_version = 3
epoch = '3.2'

[contracts.participate-stake]
path = 'contracts/participate-stake.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
