[project]
name = 'stackup'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.stackup-bounty-escrow]
path = 'contracts/stackup-bounty-escrow.clar'
clarity_version = 3
epoch = '3.2'

[contracts.stackup-grant-escrow]
path = 'contracts/stackup-grant-escrow.clar'
clarity_version = 3
epoch = '3.2'

[contracts.stackup-participation-manager]
path = 'contracts/stackup-participation-manager.clar'
clarity_version = 3
epoch = '3.2'

[contracts.stackup-project-escrow]
path = 'contracts/stackup-project-escrow.clar'
clarity_version = 3
epoch = '3.2'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
